version: '2'
services:
    ratemytutor-app:
        image: ratemytutor
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ratemytutor-postgresql:5432/rateMyTutor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://ratemytutor-elasticsearch:9200
        ports:
            - 8080:8080
    ratemytutor-postgresql:
        extends:
            file: postgresql.yml
            service: ratemytutor-postgresql
    ratemytutor-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ratemytutor-elasticsearch
